//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace modelfirstproje
{
    using System;
    using System.Collections.Generic;
    
    public partial class ForRental
    {
        public int ForRentalID { get; set; }
        public decimal Price { get; set; }
        public string Case { get; set; }
        public int LandLordLandLordID { get; set; }
        public string Name { get; set; }
        public string Location { get; set; }
    }
}
